name: Fetch Data

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  secrets: read
  
jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Check Python version
      run: python --version  # This prints the Python version

    - name: Install dependencies
      run: |
        pip install requests pandas

    - name: Fetch Data
      env:
        CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
      run: |
        echo "API Key: $CENSUS_API_KEY"  # Debugging statement
        printenv | grep CENSUS_API_KEY  # Debugging statement to print specific environment variable
        mkdir -p data  # Create data directory if it doesn't exist
        python fetch_data.py

    - name: Commit changes
      run: |
        git config --global user.name 'tcollins527'
        git config --global user.email 'tylercollins727@gmail.com'
        git add -A
        git commit -m "Automatically update census data" || echo "No changes to commit"
        git push
